"""Write web/src/lib/__fixtures__/parity.json: a small exported simulator state plus the Python engine's results,
so web/src/lib/sim.test.ts can prove the browser port reruns the exact same futures. SIMULATED data only.

Usage: uv --project engine run python scripts/make_parity_fixture.py
"""

from __future__ import annotations

import json
import tempfile
from datetime import date
from pathlib import Path

import numpy as np

from brokedate.config import REPO_ROOT, load_config
from brokedate.db import DB
from brokedate.forecast import engine as fe
from brokedate.forecast.build import export_sim_state
from brokedate.ingest.pipeline import import_statement
from brokedate.service import load_ledger
from brokedate.sim.events import Plan
from brokedate.sim.lattice import Lattice
from brokedate.sim.rollout import SimInputs


def main() -> None:
    cfg = load_config()
    cfg.gemma.enabled = False
    cfg.tabpfn.lattice_bal_points, cfg.tabpfn.lattice_s3_points, cfg.tabpfn.lattice_s14_points = 6, 2, 2
    tmp = Path(tempfile.mkdtemp())
    cfg.data_dir = tmp
    db = DB(tmp / "p.sqlite")
    import_statement(REPO_ROOT / "data" / "sim" / "statement.csv", "sim", db, cfg, use_gemma=False,
                     auto_confirm_anchors=True)
    led = load_ledger(db, cfg, "sim")
    as_of = date(2026, 8, 6)
    p = fe.prepare(led, cfg, as_of, n=60, model="lightgbm", extension_days=7)
    # round exactly as the export does, and run Python on the rounded state (what the browser sees)
    state = export_sim_state(p)
    lj = state["lattice"]
    lat = Lattice(np.array(lj["qs"]), np.array(lj["bal"]), np.array(lj["s3"]), np.array(lj["s14"]),
                  np.array(lj["values"]).reshape(lj["shape"]), p.lat.days, lj["anchor_rupees"])
    p.si = SimInputs(lat, np.array(state["day_map"]), state["H"], np.array(state["sched"]), state["bal0"],
                     np.array(state["hist14"]), state["broke_line"], np.array(state["U"]), p.si.inflow,
                     np.array(state["V"]), np.array(state["W"]))
    p.factor = np.array(state["factor"])
    plan = Plan("movie", "movie", 32000, date(2026, 8, 8), True)
    base = fe.run(p)
    with_plan = fe.run(p, [plan])
    own = fe.run(p, [plan], inflows=False)
    spend = fe.run(p, spend_today=500.0)
    out = {
        "state": state,
        "plan": {"date": "2026-08-08", "amount_paise": 32000, "active": True},
        "expected": {
            "base_first_broke": base.first_broke.tolist(),
            "plan_first_broke": with_plan.first_broke.tolist(),
            "own_first_broke": own.first_broke.tolist(),
            "spend500_first_broke": spend.first_broke.tolist(),
            "base_end_balance": np.round(base.paths[:, -1], 4).tolist(),
        },
        "note": "SIMULATED persona; generated by scripts/make_parity_fixture.py",
    }
    dest = REPO_ROOT / "web" / "src" / "lib" / "__fixtures__" / "parity.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(out), encoding="utf-8")
    print(f"wrote {dest} ({dest.stat().st_size // 1024} KB); base made it {int(base.made_it(p.H).sum())}/60")
    db.close()


if __name__ == "__main__":
    main()
